// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pangud/pangud/pkg/infrastructure/endpoint"
	"github.com/pangud/pangud/pkg/infrastructure/mapper"
	"github.com/pangud/pangud/pkg/interface/rest/resource"
)

// Injectors from inject.go:

func initEndpoint() *endpoint.RestfulEndpoint {
	db := mapper.DB()
	userResource := resource.NewUserResource()
	restfulEndpoint := endpoint.NewRestfulEndpoint(db, userResource)
	return restfulEndpoint
}
