package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/pangud/pangud/pkg/infrastructure/config"
)

var (
	//used for flags
	conf    string
	rootCmd = &cobra.Command{
		Use:   "pangud",
		Short: "pangud",
		Long: `Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.`,
	}
)

// Execute executes the root command.
func Execute() error {
	return rootCmd.Execute()
}

func init() {
	print()
	cobra.OnInitialize(initConfig)
}

func initConfig() {
	if conf == "" {
		conf = "."
	}
	config.LoadConfigFromFile(conf)
}

func print() {
	// generated by http://patorjk.com/software/taag/#p=display&f=Slant&t=pangud
	welcome := "" +
		"                                       __\n" +
		"    ____  ____ _____  ____ ___  ______/ /\n" +
		"   / __ \\/ __ `/ __ \\/ __ `/ / / / __  / \n" +
		"  / /_/ / /_/ / / / / /_/ / /_/ / /_/ /  \n" +
		" / .___/\\__,_/_/ /_/\\__, /\\__,_/\\__,_/   \n" +
		"/_/                /____/                \n"
	fmt.Println(welcome)
}
